steps:
- id: 'Build app image'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/bubbly-display-245508/github.com/gigal00p/flask-demo', '.' ]

- id: 'Push image to the registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/bubbly-display-245508/github.com/gigal00p/flask-demo"]
  waitFor: ['Build app image']

- id: 'Depl'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'deployment/mydeployment'
  - 'my-container=gcr.io/bubbly-display-245508/github.com/gigal00p/flask-demo:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kubeycluster'
  waitFor: ['Push image to the registry']
